{{- if not .Values.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "renovate-webhook.fullname" . }}
  labels:
    {{- include "renovate-webhook.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secret.webhookSecretKey }}: {{ .Values.secret.webhookSecret | quote }}
  {{- with .Values.secret.githubToken }}
  {{ $.Values.secret.githubTokenKey }}: {{ . | quote }}
  {{- end }}
{{- end }}
