apiVersion: v2
name: renovate-webhook
description: >-
  Receives GitHub webhooks and starts self-hosted Renovate runs by dispatching a
  workflow in a separate runner repository
type: application
version: 1.0.0
appVersion: 1.0.0
home: https://github.com/nonchan7720/renovate-self-hosted
sources:
  - https://github.com/nonchan7720/renovate-self-hosted
keywords:
  - renovate
  - webhook
  - dependencies
